name: Python CI

# ワークフローのトリガー設定
# workflow_dispatchイベントで手動実行を可能にする
# pushやpull_requestイベントを追加することで自動実行も可能
on:
  workflow_dispatch:

jobs:
  build:
    # ジョブの権限設定
    permissions:
      contents: read
      actions: read

    # ジョブのタイムアウト設定
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # コードをチェックアウトするステップ
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        # Pythonのセットアップステップ
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        # 依存関係をインストールするステップ
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        # テストを実行するステップ
        run: |
          set -e
          poetry run pytest tests/

  # ビルドジョブを追加することも可能
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build project
  #       run: |
  #         echo "Building the project..." 
  #         # ビルドコマンドをここに追加
  #         
  #     - name: Package project
  #       run: |
  #         echo "Packaging the project..."
  #         # パッケージングコマンドをここに追加
  
# 追加のジョブやステップを必要に応じて記述してください。