name: CI
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'テストの種類を選択してください。'
        required: true
        default: 'unit'
        options:
          - unit
          - integration
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        run: poetry build
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test ${{ github.event.inputs.test_type }}
        run: | 
          if [[ "${{ github.event.inputs.test_type }}" == "unit" ]]; then
            pytest -q --maxfail=1
          elif [[ "${{ github.event.inputs.test_type }}" == "integration" ]]; then
            pytest -q --maxfail=1 --integration
          fi
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Deploy to PyPI
        run: poetry publish --build