name: CI

on:
  # コードがpushされたときにワークフローを実行
  push:
    # すべてのブランチで実行
    branches:
      - '**'
  # その他のイベント（例: pull_request, workflow_dispatch）を追加する場合は、以下のコメントアウトを解除してください
  # pull_request:
  #   branches:
  #     - main
  # workflow_dispatch: # 手動でワークフローを実行するためのイベント

jobs:
  # ビルドとリンティングを行うジョブ
  build:
    name: Build and Lint
    # ジョブを実行するランナーのOSを指定
    runs-on: ubuntu-latest
    # ジョブのタイムアウトを10分に設定
    timeout-minutes: 10
    # ジョブに必要な最小限の権限を設定
    permissions:
      contents: read # リポジトリのコードを読み取る権限

    steps:
      # リポジトリをチェックアウトするステップ
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          # 認証情報を永続化しない設定（セキュリティベストプラクティス）
          persist-credentials: false

      # Python環境をセットアップするステップ
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          # 使用するPythonのバージョンを指定
          python-version: "3.12"
          # Poetryの依存関係をキャッシュする設定
          cache: "poetry"

      # Poetryをインストールし、仮想環境を作成しないように設定するステップ
      - name: Install Poetry
        run: |
          python -m pip install poetry
          # CI環境では仮想環境を作成せず、システムPython環境に直接依存関係をインストール
          poetry config virtualenvs.create false --local

      # プロジェクトの依存関係をインストールするステップ
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      # コードのリンティング（静的解析）を実行するステップ
      - name: Run linters (flake8, black)
        run: |
          # flake8をインストールして実行
          poetry run pip install flake8
          poetry run flake8 .
          # blackをインストールしてコードフォーマットをチェック
          poetry run pip install black
          poetry run black --check .

  # テストを実行するジョブ
  test:
    name: Run Tests
    # ジョブを実行するランナーのOSを指定
    runs-on: ubuntu-latest
    # ジョブのタイムアウトを10分に設定
    timeout-minutes: 10
    # ジョブに必要な最小限の権限を設定
    permissions:
      contents: read # リポジトリのコードを読み取る権限

    steps:
      # リポジトリをチェックアウトするステップ
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          # 認証情報を永続化しない設定（セキュリティベストプラクティス）
          persist-credentials: false

      # Python環境をセットアップするステップ
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          # 使用するPythonのバージョンを指定
          python-version: "3.12"
          # Poetryの依存関係をキャッシュする設定
          cache: "poetry"

      # Poetryをインストールし、仮想環境を作成しないように設定するステップ
      - name: Install Poetry
        run: |
          python -m pip install poetry
          # CI環境では仮想環境を作成せず、システムPython環境に直接依存関係をインストール
          poetry config virtualenvs.create false --local

      # プロジェクトの依存関係をインストールするステップ
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      # pytestを使用してテストを実行し、カバレッジレポートを生成するステップ
      - name: Run tests with pytest
        run: |
          # pytestとpytest-covをインストール
          poetry run pip install pytest pytest-cov
          # テストを実行し、カバレッジレポートをXML形式で出力
          poetry run pytest --cov=./test --cov-report=xml
