```yaml
name: Python CI

on:
  workflow_dispatch:
    # 他のイベントも追加できます
    # push:
    #   branches: [main]
    # pull_request:
    #   branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Run linters
        run: |
          poetry run flake8 .
          poetry run mypy .
          # poetry run black --check .
          # poetry run isort --check-only .

      - name: Run tests
        run: poetry run pytest

      # - name: Build package
      #   run: poetry build
      #
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist
      #     path: dist/*

```