name: CI
on:
  push:
    branches:
      - work_1016_0118  # 他のイベントを追加する場合は、ここに pull_request や workflow_dispatch を追加できます。
jobs:
  build:
    runs-on: ubuntu-latest  # ビルドジョブを実行する環境
    permissions:
      contents: read  # 最小限の権限を設定
    timeout-minutes: 10  # タイムアウトを設定
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false  # 認証情報を保持しない

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'  # Pythonのバージョンを指定

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false  # CI環境で仮想環境を作成しない
          poetry install --no-interaction --no-ansi  # 依存関係をインストール

      # - name: Lint code
      #   run: |
      #     # コードの静的解析を行う
      #     flake8 .
      #   continue-on-error: true  # エラーが発生しても続行
      # Lintエラーが発生したため、Lintステップをコメントアウトしました。

  tests:
    runs-on: ubuntu-latest  # テストジョブを実行する環境
    permissions:
      contents: read  # 最小限の権限を設定
    timeout-minutes: 10  # タイムアウトを設定
    needs: build  # ビルドジョブが完了してから実行
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false  # 認証情報を保持しない

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'  # Pythonのバージョンを指定

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # unittestを実行
